apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app: monitoring-node-cadvisor
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- daemonset.yaml
- podsecuritypolicy.yaml
- serviceaccount.yaml
